# Generated by Django 3.0.7 on 2021-06-22 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('specialization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Audience',
            },
        ),
        migrations.CreateModel(
            name='UserSpecialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('spec_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_id', to='specialization.Specialization')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_user_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserSpecialization',
            },
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mci', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aud_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_aud_id', to='specialization.Audience')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_user_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserType',
            },
        ),
        migrations.CreateModel(
            name='UserSubSpecialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_spec_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_subspec_id', to='specialization.SubSpecialization')),
                ('user_spec_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_userspec_id', to='specialization.UserSpecialization')),
            ],
            options={
                'db_table': 'UserSubSpecialization',
            },
        ),
    ]
