# Generated by Django 3.0.7 on 2021-06-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialization', '0002_audience_userspecialization_usersubspecialization_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='subspecialization',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
