# Generated by Django 3.2.4 on 2021-09-22 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specialization', '0002_advisory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('sub_spec_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_subspec_id', to='specialization.subspecialization')),
            ],
            options={
                'db_table': 'Quiz',
            },
        ),
    ]
