# Generated by Django 3.2.4 on 2021-08-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllUserAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('addimage', models.ImageField(blank=True, null=True, upload_to='alladd')),
                ('url', models.CharField(blank=True, max_length=1000, null=True)),
                ('active', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'AllUserAdd',
            },
        ),
        migrations.AlterField(
            model_name='ads',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
