# Generated by Django 3.2.4 on 2021-08-14 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topics', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'PollOption',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tos', models.TextField()),
                ('privacy_policy', models.TextField()),
                ('about_us', models.TextField()),
                ('contact_us', models.TextField()),
            ],
            options={
                'db_table': 'Settings',
            },
        ),
        migrations.CreateModel(
            name='UserPoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('poll_option_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polloption', to='poll.polloption')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserPoll',
            },
        ),
        migrations.CreateModel(
            name='TopicPoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('number_of_options', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_topic', to='topics.topics')),
            ],
            options={
                'db_table': 'TopicPoll',
            },
        ),
        migrations.AddField(
            model_name='polloption',
            name='topic_poll_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_option', to='poll.topicpoll'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Feedback',
            },
        ),
    ]
