# Generated by Django 3.2.4 on 2021-09-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20210816_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=10000)),
            ],
            options={
                'db_table': 'ContactUs',
            },
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='reason',
            field=models.CharField(blank=True, choices=[('Bug', 'Bug'), ('Suggestion', 'Suggestion'), ('Other', 'Other')], max_length=20, null=True),
        ),
    ]
