# Generated by Django 3.2.4 on 2021-08-19 05:39

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20210816_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accomplishments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='accomplishment')),
                ('publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('publicationdate', models.DateField(blank=True, null=True)),
                ('authors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None)),
                ('publication_url', models.CharField(blank=True, max_length=3000, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='acc_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Accomplishments',
            },
        ),
    ]
