# Generated by Django 3.2.4 on 2021-09-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20210916_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
