# Generated by Django 3.2.4 on 2021-08-14 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import topics.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('specialization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoeries',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to=topics.models.get_image_path)),
            ],
            options={
                'db_table': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic_audience', models.CharField(choices=[('doctor', 'doctor'), ('general', 'general')], max_length=20)),
                ('format', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=2)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1000)),
                ('deliverytype', models.CharField(blank=True, choices=[('pdf', 'pdf'), ('external', 'external')], default='external', max_length=20, null=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to=topics.models.get_pdf_path)),
                ('pdfsecond', models.FileField(blank=True, null=True, upload_to='pdfsecond')),
                ('source_url', models.CharField(blank=True, max_length=255, null=True)),
                ('external_url', models.CharField(blank=True, max_length=255, null=True)),
                ('media_type', models.CharField(blank=True, choices=[('image', 'image'), ('video', 'video')], max_length=20, null=True)),
                ('video_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('publishingtime', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='author_profile', to=settings.AUTH_USER_MODEL)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_category', to='topics.categoeries')),
            ],
            options={
                'db_table': 'Topics',
            },
        ),
        migrations.CreateModel(
            name='UserCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_user_id', to='topics.categoeries')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_category', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserCategory',
            },
        ),
        migrations.CreateModel(
            name='TopicSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Topic_specialization', to='specialization.specialization')),
                ('topic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_topic', to='topics.topics')),
            ],
            options={
                'db_table': 'TopicSpecialization',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to=topics.models.get_image_path_topic)),
                ('topic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_image', to='topics.topics')),
            ],
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_topic', to='topics.topics')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Favourite',
            },
        ),
    ]
