# Generated by Django 3.2.4 on 2021-06-30 07:24

from django.db import migrations, models
import topics.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoeries',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to=topics.models.get_image_path)),
            ],
            options={
                'db_table': 'Categories',
            },
        ),
    ]
