# Generated by Django 3.2.4 on 2021-09-22 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specialization', '0002_advisory'),
        ('topics', '0002_alter_topics_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicSubSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subspec_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Topic_subspecialization', to='specialization.subspecialization')),
                ('topic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_subspec', to='topics.topics')),
            ],
            options={
                'db_table': 'TopicSubSpecialization',
            },
        ),
    ]
