# Generated by Django 3.2.4 on 2021-10-22 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_topicsubspecialization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topics',
            name='author',
        ),
    ]
