# Generated by Django 3.2.4 on 2021-06-30 05:59

import django.core.files.storage
from django.db import migrations, models
import topics.models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0004_categoeries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoeries',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/media/categories'), upload_to=topics.models.get_image_path),
        ),
    ]
